spring:
  datasource:
    driver-calss-name: com.mysql.cj.jdbc.Drive
    url: jdbc:mysql://192.168.150.131:3306/mushan-admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      pool-name: DateHikariC
      minimux-idle: 5
      idel-timeout: 18000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1